version: '3'
services:
  personal-automation-api:
    image: dylansheffer/personal-automation-api:latest
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped